### ISSUE TITLE
yaft as a getty replacement

### ISSUE THREAD

**Issue by Happy-Ferret** [uobikiemukot/yaft#3]
Is there a way to use yaft as a getty replacement? 
Replacing "/sbin/getty" with "/usr/bin/yaft" inside /etc/inittab doesn't seem to work and "openvt yaft" ends up making the newly spawned vt unusable. 

I'd like to play a video or display a small gif during the initial startup of my Debian system and then, once it's finished, switch to another tty.

**Comment by uobikiemukot** [comment]
yaft is not getty replacement.
please try other programs, like fbgetty (show image on login prompt) or fbsplash (show image on boot).
