### ISSUE TITLE
customize size

### ISSUE THREAD

**Issue by bryfry** [uobikiemukot/yaft#39]
I have a separate fb program which uses the last (single) column of pixels on the screen to display a battery percentage bar.  When fb refreshes overwrites these pixels.  Would it be possible to change somewhere in yaft to not write to these pixels and to only see the screen size as 1 pixel less in with?

Thanks!

**Comment by uobikiemukot** [comment]
Hi,

> Would it be possible to change somewhere in yaft to not write to these pixels and to only see the screen size as 1 pixel less in with?

Currently yaft does not support custom size feature, always uses whole screen.

I recommend to use text based status monitor programs (like i3status variants) and
 screen/tmux status line feature.

---

in a special cases, yaft does not draw at the bottom of display:
-  for example, If font height equals 15 pixels  and display height equals 29 pixels, yaft does not draw 14 pixels at the bottom

Or If you are willing to rewrite some codes, you can use this patch:
(drop the last terminal lines in this example)

~~~diff
diff --git a/yaft/terminal.c b/yaft/terminal.c
index b4455c3..def74a3 100644
--- a/yaft/terminal.c
+++ b/yaft/terminal.c
@@ -352,7 +352,7 @@ bool term_init(struct terminal_t *term, int width, int height)
        term->height = height;

        term->cols  = term->width / CELL_WIDTH;
-       term->lines = term->height / CELL_HEIGHT;
+       term->lines = term->height / CELL_HEIGHT - 1;

        term->esc.size = ESCSEQ_SIZE;
~~~

**Comment by bryfry** [comment]
Yep, that's what I'm planning on switching to. I was previously just using
the Linux console and it never touched that last column of pixels so I used
that for my own fb app. Thanks for your response!
