### ISSUE TITLE
yaft becomes unusable after switching ttys

### ISSUE THREAD

**Issue by HalosGhost** [uobikiemukot/yaft#5]
For example, if I launch X as normal on tty1 and then switch to tty2 and launch yaft. If I switch to tty1 and then back to tty2 (switch from yaft to X and then back), the screen is completely blank and I can do nothing except hit ``^D`` to exit yaft which will take me back to getty.

Doing anything else causes nothing to be drawn to the screen.

**Comment by tb01110100** [comment]
Can reproduce.

**Comment by uobikiemukot** [comment]
Switching from linux console to yaft is work, but switch from X to yaft is not.
I'm trying to fix this.

**Comment by HalosGhost** [comment]
:+1:

**Comment by uobikiemukot** [comment]
Please checkout develop branch, and set FORCE_TEXT_MODE as true in conf.h.

**Comment by HalosGhost** [comment]
Rocking! That solves the problem for me! Fixed via 71ac8b7
